version: '3'
services:
  opensga:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      SGA_USERNAME: ${SGA_USERNAME}
      SGA_PASSWORD: ${SGA_PASSWORD}
